version: '3'
services:
  ycsb_project:
    build: .
    volumes:
      - ./src:/app
      - ./results:/app/results
    working_dir: /app
    command: bash -c "python main.py && python bayes_runtime.py"
